import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <Layout>
        <body className={inter.className}>{children}</body>
      </Layout>
=======
      <body>
        <Layout>
          {children}
        </Layout>
      </body>
>>>>>>> main
    </html>
  );
}
